version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: dockermikky/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/static
  frontend:
    image: dockermikky/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: dockermikky/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
    ports:
      - 9000:80
    depends_on:
      - db
